[package]
name = "parallel-image-processing-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
pixels = "0.13"
rand = "0.8"
rand_chacha = "0.3"
tao = { version = "0.28", features = ["rwh_05"] }
