[package]
name = "parallel-image-processing-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
env_logger = "0.11.5"
pixels = "0.13.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
tao = { version = "0.28.1", features = ["rwh_05"] }
