[package]
name = "parallel-image-processing-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
pixels = "0.15"
rand = "0.8"
rand_chacha = "0.3"
winit = { version = "0.30" }
